### ISSUE TITLE
perl getopt:mixed obsoleted, advice is to use getopt:long

### ISSUE THREAD

**Issue by radoeka** [Ankzz/getBondStatus#3]
For newer linux versions getopt:mixed is no longer available (as package.

According to the getopt:mixed homepage https://metacpan.org/pod/Getopt::Mixed is obsoleted:

"use Getopt::Long 2.17; # Released with Perl 5.005Getopt::Long::Configure(qw(bundling no_getopt_compat));GetOptions(...option-descriptions...);"

Can you please change the argument processing and have it use the perl getlong module.

Thanks.

**Comment by Ankzz** [comment]
Thanks for the update. Shall quickly look into it.

**Comment by Ankzz** [comment]
Updated the code to use Getopt::Long with my latest commit.
Thanks for raising this issue.
