### ISSUE TITLE
Argument -l does not work as expected

### ISSUE THREAD

**Issue by radoeka** [Ankzz/getBondStatus#8]
The command does not output anything when only -l argument is used:

```
host01# ./getbondstatus -l
host01# ./getbondstatus -l -v
host01# ./getbondstatus -v -l
Bonds: bond0
```
As you can see only when -v is listed as first argument there is output.

The other arguments seem to work fine.

**Comment by Ankzz** [comment]
Will fix it.
Seems some issue due to last refactoring.

**Comment by Ankzz** [comment]
Done with the latest commit.
