### ISSUE TITLE
Output -S argument - rearrange some info

### ISSUE THREAD

**Issue by radoeka** [Ankzz/getBondStatus#9]
When comparing the output provided by cat /proc/net/bond0 and getbondstatus information could be put in another section:

```
# ./getbondstatus -S bond0
    Down Delay (ms): 0
    Up Delay (ms): 0
    Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)
    MII Status: up
    slave_count: 2
    Bonding Mode: fault-tolerance (active-backup)
    Primary Slave: None
    speed: 2 Gbps
    Slaves1 =>
        Duplex: full
        Slave queue ID: 0
        Link Failure Count: 7
        Speed: 1000 Mbps
        Slave Interface: eno50
        Permanent HW addr: .................
        MII Status: up
    Slaves2 =>
        Duplex: full
        Slave queue ID: 0
        Link Failure Count: 0
        Speed: 1000 Mbps
        Slave Interface: eno49
        Permanent HW addr: .................
        MII Status: up
    Currently Active Slave: eno50
    MII Polling Interval (ms): 100

```
Slaves1 and Slaves2 should be Slave1 and Slave2 or Slave 1 and Slave 2

The lines:
```
    Currently Active Slave: eno50
    MII Polling Interval (ms): 100
```
Are better positioned in the top section, with the general common bond information (the first lines of the output)

It would be good to start the slave section with the slave interface ID:
```
    Slave 2 =>
        Slave Interface: eno49
        Duplex: full
        Slave queue ID: 0
        Link Failure Count: 0
        Speed: 1000 Mbps
```

Would it be possible to provide a tabel output mode?  Like so:

```
bond | slave | interface | status |mode  | queue ID | fail count | speed ...
0    | 1     | eno49     | up     | full | 0        | 0          |   1000 Mbps
0    | 2     | eno50     | down   | full | 0        | 0          |   1000 Mbps    

```

That would allow for a very quick lookup when something is wrong

**Comment by Ankzz** [comment]
Would look into this. But would take some time as currently I do not have a setup with bond interfaces.
Without testing would not like to commit.

Can you raise a pull request for the same. 
Would design it to add another parameter for the new output format like an option "-o", if specified can detail the output as you suggested.

Also, for the name of Slave interface to be specified first, it would need some intrinsic changes in the logic how I am detailing out a Slave interface and is currently generic in nature.

Agree to your suggestion of displaying the Slave interface name first.
If you can take care of this also as part of your pull-request, I would be more than happy to accept the merge.

Silly but another option, if you could lend me your bonded system for testing, I would update the code myself. But I think this option won't be available. But just asked in case.

**Comment by radoeka** [comment]
-o option to define the output sounds good.  Could use --output (-o) table, table-all, csv for respective a table with most important data (keeps the table small), all data (wide table), and a comma separated value file, for easy processing.

I've no code available, and as I'm happy to be able to write the tickets for the issues I found I don't expect that I'll be able to do so (I'm nor good with perl).

**Comment by Ankzz** [comment]
No issues .. I would work on your suggestions and would provide you the updated tool asap. 
Would like to be kept updated on the feedback and performance and utility of this tool.

**Comment by Ankzz** [comment]
I have fixed a few defects reported by you as part of #11 commits.
Will be working on the -o option and would update once done.

Regarding the default action , I have currently kept it aligned to as most of the standard tools report their help message when executed without any parameters.

**Comment by Ankzz** [comment]
@radoeka : I have merged my code with -o option as part of #12 commit.
Do update me on the same.
-o option currently takes only two options default/table

./bond -o table -i bond0

**Comment by Ankzz** [comment]
Committed changes for removing spaces #13

**Comment by Ankzz** [comment]
Closing for now. Not heard back from @radoeka on feedback.
If this is not working or someone feels like this needs to reopen, please do so.
Or in the interest of project would request to create a new ticket.
